### ISSUE TITLE
aws data lake API query reference

### ISSUE THREAD

**Issue by damdr** [awslabs/aws-data-lake-solution#15]
Hello 

just like the "CLI command reference" located [here](http://docs.awssolutionsbuilder.com/data-lake/cli/cli-datalake/) is it possible to have a description and an example for each API?

maybe you have already created this documentation?

**Comment by hvital** [comment]
Hi damdr.

The project does not have a specific content for the API yet. Probably the most complex step in order to send request to the API layer is how to sign them but you can use CLI implementation as reference: https://github.com/awslabs/aws-data-lake-solution/tree/master/source/cli 

Does it help?

It's also recommend to take a look at how front-end factories were implemented: https://github.com/awslabs/aws-data-lake-solution/tree/master/source/console/app/common/factories
