### ISSUE TITLE
Upgrading andexisting installation

### ISSUE THREAD

**Issue by lkbodine** [awslabs/aws-data-lake-solution#3]
Is there way to upgrade the Elasticsearch version of an existing Data Lake installation?

**Comment by shsenior** [comment]
@lkbodine you can follow the process identified [here](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html) to upgrade the Amazon Elasticsearch Service Cluster from 2.3 to 5.1. The data lake has been tested with 5.1 and currently deploys with 5.1.

Once you have complete the upgrade of the Amazon Elasticsearch Service Cluster, you will need to manually update the application setting for the Amazon Elasticsearch Service Cluster Endpoint URL in the **data-lake-settings** Amazon DynamoDB table. Open the item with the **setting_id** of app-config and modify the **esurl** attribute in the **setting** map to the new Amazon Elasticsearch Service Cluster Endpoint URL from the 5.1 cluster.

Ensure you name the new 5.1 cluster domain **data-lake**, otherwise, you will need to update the IAM policy as well.
